### ISSUE TITLE
Collision detection fails when collision polygon lies outside of entity

### ISSUE THREAD

**Issue by benbarefield** [craftyjs/Crafty#412] opened 2013-02-01 01:54 UTC
I'm not sure if this is intended behavior or not, but if you define a collision polygon larger than the object that it is attached to, it will not get picked up in a call to .hit. In my reading of .hit:
It first does a broad search for objects intersecting with the rectangle that is defined by the objects x/y coordinates and height/width:

``` javascript
results = Crafty.map.search(area, false),
```

Then it runs the SAT collision calculations only if the broad phase search returned results:
So, if you do something like (where SomeSprite is a 5x5 sprite you've already set up):

``` javascript
Crafty.e("2D, DOM, SomeSprite, Collision, Test").attr({ x: 5, y : 5})
         .collision([0, 0], [10, 0], [5, 5], [0, 5]);
var other = Crafty.e("2D, DOM, SomeSprite, Collision").attr({ x : 8, y : 8 });
var hits = other.hit("Test");
```

hit won't have any results.

**Comment by benbarefield** [comment] 2013-02-05 06:21
This is the same issue as:
https://github.com/craftyjs/Crafty/issues/149
Sorry.

**Comment by jumpcoder** [comment] 2013-06-17 13:16
the entity named "other" maybe has some problem ,because the .init() of Collision has be called before .attr({x:8, y:8}), Accoding to the document "You must ensure that the x, y, w, h properties are set before the init function is called. "

**Comment by starwed** [comment] 2013-06-17 15:54
@jumpcoder  This is a somewhat separate issue.  When doing collision detection, Crafty does a first pass broad search where it finds entities that are near the entity you're testing.  Then it tests for collisions using a more exact method.  

But since it uses an object's MBR for the broad pass, making the collision hitbox larger than the MBR will mess things up.

(Unrelated to this bug, the issue you mention is now finally fixed in develop!  It caused me a lot of grief when I was first learning Crafty.)

**Comment by icco** [comment] 2013-11-17 07:34
I'm seeing the same issue as @benbarefield.

**Comment by icco** [comment] 2013-11-17 08:46
Just to be clear, I'm seeing this in both head and in the 0.5.4 release.

**Comment by starwed** [comment] 2013-12-14 18:45
I made a [jsfiddle](http://jsfiddle.net/c3597/7/) that illustrates the problem in 0.6.1.

**Comment by grozen** [comment] 2013-12-16 09:23
I saw you mention on the groups thread that this is tricky to solve performance-wise.
While I am completely unaware of the specifics, can't we just do the MBR pass on the entities **or** their hitboxes? As in, prefer the associated hitbox's MBR if a hitbox is defined?

From my specifics-agnostic viewpoint this seems alright in the performance sense. Of course, this may be a nightmare to implement if I were to consider the specifics.

**Comment by starwed** [comment] 2013-12-16 16:45
> While I am completely unaware of the specifics, can't we just do the MBR pass on the entities or their hitboxes? As in, prefer the associated hitbox's MBR if a hitbox is defined?

Unfortunately the MBR is used not just for collision detection, but also to determine what areas to redraw when a "Canvas" entity moves.  

Crafty maintains a map of which entities are in each cell of the stage -- a cell by default being a 32 by 32 pixel area.  When we check an entity _e_ for collisions, to avoid checking against _every other entity_ on the stage, it first compiles a list of entities which share a cell with _e_.  If you read about collision algorithms, this is typically called a "broad phase" pass.

Something very similar occurs when drawing _e_ -- because of the way canvas works, we'll need to redraw every entity that overlaps with _e_, which requires pretty much the same check.  So currently it is _exactly_ the same check.

Complicating things is that we should probably support manually specifying a render region that overrides the MBR.  The most common use case I've seen mentioned is adding a glow or shadow around an entity.

Searching for overlapping entities is already one of the more processor intensive parts of crafty, so I want to make sure it doesn't get worse for the normal use case.  This should definitely be doable, but might require a bit of thought.  :)

**Comment by grozen** [comment] 2013-12-17 09:41
Thanks for the in-depth explanation!

**Comment by starwed** [comment] 2013-12-17 20:33
> Complicating things is that we should probably support manually specifying a render region that overrides the MBR. The most common use case I've seen mentioned is adding a glow or shadow around an entity.

This turns out not to be an issue -- after thinking about it, this just redefines what the MBR is.  I put together a patch that seems to work, and would allow a workaround for this issue as well.

I started putting together a patch for this issue too, but the problem is that you have to recalculate things every time the collision hitbox rotates -- that seems like it could hurt performance.  Luckily we don't have to be super-exact here, and it's ok to overestimate the area, so I have a couple of ideas that might work without hurting the normal use case.

**Comment by starwed** [comment] 2013-12-17 22:58
We can calculate a (non-minimal) bounding box for the collision polygon as follows:
- Find the minimal bounding box of the entity+collision map when _unrotated_.  We can just do this once when the collision map is attached.
- Store the center and radius of the minimal bounding circle for that rectangle.
- On rotation, transform that central point.
- When updating the MBR, find the minimal square that fits round that circle, then find the minimal rectangle around square+MBR
- update the entity's position in the broad phase hashmap based on that rectangle

Then when a custom polygon is attached as a map, we do a check to see if it's out of bounds -- if it is, a flag is set.  That means we can skip all of the above except when that flag is true.  So we'd avoid any expensive checks except in the case where a custom polygon is set.

You can pretty easily see that no matter how it rotates, the collision polygon will stay within the bounding circle.  The bounding square of that circle will be larger than the minimal bounding rectangle but be faster to calculate. (Just look at `_calculateMBR`  -- we'd have to do most of that twice to accurately track the minimal collision rectangle.)

Maybe there's a way to very quickly calculate the MBR of the map+entity in a way that piggy backs off the existing method, but I'm unable to see it.

**Comment by starwed** [comment] 2013-12-19 05:09
Ok, I implemented the idea above, and it seems to work.  It adds an additional property called `_cbr` that can be used for bounding collisions.

I need to make sure I'm not accidentally messing up performance in the standard case, and that the _cbr stuff is handled properly in some edge cases.

**Comment by kevinsimper** [comment] 2013-12-25 10:41
| The bounding square of that circle will be larger than the minimal bounding rectangle but be faster to calculate. 

How can that be? A circle is normally round which would make the rectangle and the square the same size.

**Comment by starwed** [comment] 2013-12-25 22:43
Compared to the minimal bounding rectangle of the hitbox, not the circle.

**Closed as completed** 2013-12-30 21:06 UTC
Labels: kind: bug/fix
