### ISSUE TITLE
addCompontent triggers Move Event

### ISSUE THREAD

**Issue by przor3n** [craftyjs/Crafty#363] opened 2012-10-15 10:41 UTC
Code: 

  var bricksMoving = 0;
  var jewels = new Array();

window.onload = function() {
  var howMany = 4;

  // Start crafty
  Crafty.init(600, 600);

  Crafty.background("#fff");

  Crafty.sprite(32, "images/0.png", { s0: [0, 0]} );
  Crafty.sprite(32, "images/1.png", { s1: [0, 0]} );
  Crafty.sprite(32, "images/2.png", { s2: [0, 0]} );
  Crafty.sprite(32, "images/3.png", { s3: [0, 0]} );
  Crafty.sprite(32, "images/4.png", { s4: [0, 0]} );
  Crafty.sprite(32, "images/5.png", { s5: [0, 0]} );
  Crafty.sprite(32, "images/6.png", { s6: [0, 0]} );
  Crafty.sprite(32, "images/7.png", { s7: [0, 0]} );
  Crafty.sprite(32, "images/8.png", { s8: [0, 0]} );
  Crafty.sprite(32, "images/9.png", { s9: [0, 0]} );

  function generateWorld() {  
        for (var i = 0; i < 8; i++) {
            jewels[i] = new Array();
            for (var j = 0; j < 8; j++) {

```
            type = Crafty.math.randomInt(1, howMany);
            jewels[i][j] = Crafty.e("2D, DOM, s" + type)
                .attr({ x: j * 32 + 3, y: i * 32 + 3 })              
                .bind("Move", function(){
                console.log(bricksMoving);
        bricksMoving--;
            });           
        }
    }

    Crafty.e("2D, DOM, solid").attr({ w: 300, h: 10, x: 0, y: 260 });        

}  
```

  Crafty.scene("loading", function () {
    //load takes an array of assets and a callback when complete
    Crafty.load(["images/9.png"], function () {
        Crafty.scene("main"); 
    });   

```
Crafty.e("2D, DOM, Text").attr({ w: 100, h: 20, x: 150, y: 120 })
        .text("Loading")
        .css({ "text-align": "center" });
});


//automatically play the loading scene
Crafty.scene("loading");     
var sa = Crafty.scene("main", function () {
    generateWorld()

});
```

END OF CODE;

If you do jewels[0][0].removeComponent the Move event isn't triggered , then when you do jewels[0][0].addComponent it triggers that event. 

I didn't found that in docs , so I think it's a bug.

**Comment by hugeen** [comment] 2012-10-15 13:14
I could be wrong but I think it's coming from:

``` javascript
.attr({ x: j * 32 + 3, y: i * 32 + 3 })    
```

**Comment by przor3n** [comment] 2012-10-15 13:29
this is done only on start, when you init all objects. it is also method from 2D component and uses local variables i and j . the event is triggered when you add the "s[0..9]" components when the script is done.  this is sprite , but sprites have Change event, not Move

**Comment by starwed** [comment] 2013-04-25 02:05
This is caused by the"s[0..0]" component setting `_w` and `_h`.    (Look at the `init` method of the component created by Crafty.sprite.)  Setting the width and height on a "2D" component triggers a "Move" event.

The root problem here is that when `_w` and `_h` (or `_x` and `_y`) are set via `_attr()`, Crafty doesn't check whether they've actually changed before triggering a "Move" event.    I think this should be considered a bug.

**Comment by starwed** [comment] 2013-05-14 19:28
This should be fixed in develop now?  If anyone still sees this behavior, please reopen the issue!

**Closed as completed** 2013-05-14 20:21 UTC
