### ISSUE TITLE
npm craftyjs dependency error

### ISSUE THREAD

**Issue by A-ZC-Lau** [craftyjs/Crafty#1157] opened 2017-10-21 11:59 UTC
Getting the following error when I try to import it:
```
This dependency was not found:

* fs in ./~/craftyjs/src/graphics/color.js, ./~/craftyjs/src/graphics/image.js and 1 other

To install it, you can run: npm install --save fs
```

Any known work arounds or future fixes?

**Comment by starwed** [comment] 2017-10-29 18:19
>Getting the following error when I try to import it

Possibly dumb question (I don't really have much experience actually using crafty as an npm module) -- what specifically are you importing?  For concreteness, could you give the exact code that triggers the error?

**Comment by A-ZC-Lau** [comment] 2017-10-29 20:27
Hmm, well I'm using it in combination with Vue.js, so that might be an issue too. I believe I was just doing a standard `import 'craftyjs'` or `require('craftyjs')`

**Comment by starwed** [comment] 2017-11-05 21:57
I tried updating [this example](https://github.com/kevinsimper/craftyjs-npm-example) to use crafty `0.8.0`, and it seemed to work correctly.

Maybe following the pattern of that example will help?

**Comment by lau-a** [comment] 2017-11-05 22:09
I'll try it again in the future.

**Comment by starwed** [comment] 2018-01-13 18:29
Closing, since I couldn't reproduce.

(But anyone should feel free to reopen if they run into this issue.)

**Closed as completed by starwed** 2018-01-13 18:29 UTC

**Comment by falnos24865** [comment] 2019-01-06 03:04
Pinging this issue as I get this same error in both 0.8.0 and 0.9.0. Looking at the code I see that 

- src/graphics/color.js
- src/graphics/image.js
- src/graphics/sprite.js

 have a `var fs = require('fs')` line in them, which is likely the issue.

**Comment by falnos24865** [comment] 2019-01-06 03:14
Just to give a bit more context: I ran into this issue when using the `npm` module `craftyjs`. When I downloaded the production version of Craft and used that, it works. So likely an issue with the `npm install craftyjs` setup.
