### ISSUE TITLE
Problems when trying to keep entities between scenes with Persist

### ISSUE THREAD

**Issue by Wanderer101** [craftyjs/Crafty#1052] opened 2016-09-25 01:16 UTC
Howdy folks!

I'm currently developing an isometric game in which I'm having some problems figuring out how to "preload" the isometric level before changing the scene. Basically, I have a scene called "loading" in which I load my assets, and then I cut to the main scene in which I am building the isometric map with the Tiledmapbuilder component. However, I'd prefer to build the scene during the loading phase, but I can't seem to get it to work even when using the "Persist" component. Is there someone who has some tricks for this type of thing?

**Comment by starwed** [comment] 2016-09-25 18:26
> I can't seem to get it to work even when using the "Persist" component.

Hmm, that should work to prevent the entities from being destroyed; you can see the logic [here](https://github.com/craftyjs/Crafty/blob/develop/src/core/scenes.js#L145-L147)  What sort of problems are you running into?

(It might be simplest to avoid using scenes for this, if you plan on having all your entities persist over the scene transition in any case.)

_e:_ Fix link.

**Comment by starwed** [comment] 2016-12-13 03:25
Closing since it's not reproducible, but feel free to repopen.

**Closed as completed by starwed** 2016-12-13 03:25 UTC
