### ISSUE TITLE
If you place a entity A on the entity B,then entity B mouse/drag event error

### ISSUE THREAD

**Issue by yiyuezhuo** [craftyjs/Crafty#965] opened 2015-10-06 11:29 UTC
Yes,It's fuzzy for this the overlap trigger it or not.But you can found the situation in some war game call "stack".In this you can click a unit in the stack under the another to top it .In the other word, I think that overlap should be trigger the top one without a error.

**Comment by starwed** [comment] 2015-10-11 18:41
Hi, I'm a little unclear on what the problem is.  Could you clarify the issue, or provide an example?

**Comment by starwed** [comment] 2016-09-30 18:02
Closing since the issue is unclear.  (Feel free to reopen if a problem still exists!)

**Closed as completed by starwed** 2016-09-30 18:02 UTC
