### ISSUE TITLE
Canvas scale and context.imageSmoothingEnabled

### ISSUE THREAD

**Issue by Jasz** [craftyjs/Crafty#330] opened 2012-07-29 16:31 UTC
Pixel art is quite popular, especially in web games, since low-res graphics are faster to load. But if we work with graphics so small they need to be scaled. What do you think about including Crafty.canvas.scale(x [, y]) that would call context.scale(x,y)? Also, by default, browsers use some kind of image smoothing in canvas when scaled. What do you think of adding Crafty.canvas.imageSmoothingEnabled(enable), and set enable to context.mozImageSmoothingEnabled (Firefox 3.6+) and context.webkitImageSmoothingEnabled (Chrome 21+). I'm a beginner, but if someone would be kind enough to correct me later I'd be happy to do that.

**Comment by BlackScorp** [comment] 2012-07-29 18:54
it called Zoom in crafty Crafty.viewport.zoom(2) for example, but i dont know if it works kurrently

**Comment by Jasz** [comment] 2012-07-29 19:39
I guess it works if someone is actually using viewport.

**Comment by UltCombo** [comment] 2013-09-16 06:56
Scaling is already implemented through `Crafty.viewport.scale()`. +1 for `imageSmoothingEnabled`, other game abstraction libraries have it and it is really useful for pixel art games.

**Comment by mucaho** [comment] 2013-12-24 11:32
some links:
[StackExchange: alternatives to specifying image smoothing](http://stackoverflow.com/questions/10525107/html5-canvas-image-scaling-issue)
[Image rendering with CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering)

**Comment by mucaho** [comment] 2013-12-24 20:33
Executing the following code smooths the image for Chrome, but it does not work for Firefox:

``` javascript
Crafty.init(600, 300);

Crafty.canvas.init();
Crafty.canvas.context.imageSmoothingEnabled = false;
Crafty.canvas.context.mozImageSmoothingEnabled = false;
Crafty.canvas.context.webkitImageSmoothingEnabled = false;
Crafty.canvas.context.msImageSmoothingEnabled = false;

Crafty.background('rgb(0,0,0)');
Crafty.viewport.scale(6);

var ent = Crafty.e("2D, Canvas, Image")
    .image("squares.gif")
    .bind("Draw", function(e) {});

```

However look at this [jsfiddle](http://jsfiddle.net/VAXrL/190/). Even if you remove all CSS statements and keep only the Javascript statements, the image gets smoothed (even for FF).

Some internal Crafty statements must work against the image smoothing on FF. Any ideas? @starwed?

**Comment by starwed** [comment] 2013-12-24 21:26
> Executing the following code smooths the image for Chrome, but it does not work for Firefox:

To be clear, you _don't_ want it to be smoothed, right?

**Comment by starwed** [comment] 2013-12-24 21:38
Your fiddle was using a different technique to render the sprite than the "image" component uses.  [Here](http://jsfiddle.net/h5mCt/) is an example that follows what "Image" does, and reproduces the same issue in Firefox.

**Comment by starwed** [comment] 2013-12-24 21:43
And [here](http://jsfiddle.net/h5mCt/1/) is a fiddle that uses the same method the "Sprite" component uses.  (Which is basically what you were doing, but instead of scaling the image the entire canvas context is scaled instead.)  It shows crips pixels Firefox, Chrome, and Safari.

So the issue seems to be that Firefox doesn't respect the smoothing options when filling a rectangle with a pattern.

**Comment by mucaho** [comment] 2013-12-24 22:05
> To be clear, you don't want it to be smoothed, right?

Yeah exactly :)

> So the issue seems to be that Firefox doesn't respect the smoothing options when filling a rectangle with a pattern.

Good catch. Should I go ahead and extend Crafty with `Crafty.canvas.setImageSmoothing(boolean enabled): void` anyway (and we just add a note in the docu saying it does not work with FF insert_current_version)?
I will go ahead and submit the bug to Firefox.

**Comment by mucaho** [comment] 2013-12-24 22:10
Actually the issue has already been reported: [Bugzilla Bug#696630](https://bugzilla.mozilla.org/show_bug.cgi?id=696630)

**Comment by starwed** [comment] 2013-12-24 23:11
> Actually the issue has already been reported: Bugzilla Bug#696630

Nice find -- I'm terrible at using bugzilla, so had opened a new issue I just closed as a dupe of that one.  :)

**Closed as completed** 2014-01-06 01:53 UTC
