### ISSUE TITLE
Keyboard keydown event error

### ISSUE THREAD

**Issue by potomak** [craftyjs/Crafty#606] opened 2013-11-06 11:55 UTC
I'd like to subscribe to the `KeyDown` event but it's never triggered as `Crafty.trigger("KeyDown", e);` iff `Crafty.keydown[e.key] !== true` and the assignment is made inside the same conditional block.

See https://github.com/craftyjs/Crafty/blob/develop/src/controls.js#L292-L295

**Comment by starwed** [comment] 2013-11-06 15:41
In practice, when does this come up?  Can you have two keydown events of the same type without a key up event in between?

**Comment by mucaho** [comment] 2013-11-07 00:09
Perhaps my experience is related to yours:
I tried to listen to key events locally at an entity with `Crafty.e("..., Keyboard, ...").bind("KeyDown",  function(){})` but it didn't work for me. The _fix_ was to listen to key events globally with `Crafty.bind("KeyDown",  function(){})`
I was pretty newb to crafty back then, so I might have done something wrong.

**Comment by starwed** [comment] 2013-12-11 03:45
I'm still a bit confused on what the issue is here.  Could someone take a stab at explaining it?

**Comment by starwed** [comment] 2013-12-14 18:50
Closing, since I don't see the described bug -- but totally willing to reopen if I'm just not understanding the issue.

**Closed as completed by starwed** 2013-12-14 18:50 UTC
