### ISSUE TITLE
collision detection with big polygons

### ISSUE THREAD

**Issue by sorenbs** [craftyjs/Crafty#149] opened 2011-12-02 06:15 UTC
When a polygon that is larger than the entity is used for collision detection, collision is only detected for the part of the polygon that is inside the entitys bounding box.

In this example a circle is used:
http://jsfiddle.net/yUPdt/1/

I think the problem is that when we search for potential colliding entities in the hash map the filtering is done on the bounding box of the entity and not the polygon.

**Comment by abuisman** [comment] 2013-01-20 00:14
Has there been any progress on this?

**Comment by starwed** [comment] 2013-04-24 05:58
Closing as a dupe of #412.  (Clearer example code in that one.)

**Closed as completed by starwed** 2013-04-24 05:58 UTC
