### ISSUE TITLE
Setting entity.visible = false sometimes makes other present entities invisible

### ISSUE THREAD

**Issue by danielmoniz** [craftyjs/Crafty#817] opened 2014-09-18 19:07 UTC
I'm making a war strategy game using Crafty and am working on fog of war. I was getting problems with seemingly random (though consistent; the same pieces seem to disappear, but their location seems random) stretches of road, grass, etc. would disappear.

I confirmed this by commenting out all code except for a very specific function. I am selecting entities by component 'Shadow', which is overlayed on top of 'FakeGrass', with z values 2 and 1 respectively. Shadow also requires the FakeGrass component.

The idea was to make the Shadow tiles invisible when players are near them, thereby illuminating the fog. I've since changed to using transparency (alpha) and am setting the Shadow to alpha = 0 when players are nearby. I have since had zero issues with this problem.

I have confirmed that only Shadow tiles are being made invisible by looking for entities that do not have Shadow as a component. I have also triple checked the z-values, and none are being modified during the game.

Other notes:
- the tiles are made visible again by clicking on them
- the tiles often seem to be grouped (eg. I often get a black 3x3 square)
- it will remove any other co-located entity (I've seen villages, roads, grass, and trees disappear)

I have since moved on and am successfully using alpha. In case this does get looked into, I've left some code below. I can supply more code if needed.

```

LineOfSight = {
  tileLineOfSight: function(side) {
    this.allEntitiesVisible('Shadow');  // starting by re-adding fog before removing areas near friendly units
    var tiles_in_sight = this.getGenericEntitiesInSight('Shadow', side);
    for (var i=0; i<tiles_in_sight.length; i++) {
      var tile = tiles_in_sight[i];
      if (!tile.has('Shadow')) {
        console.log("tile.type");   // these two lines never print
        console.log(tile.type);
      }
    }
    this.makeInvisible(tiles_in_sight);
    return this;
  },

makeInvisible: function(entities) {
    for (var i=0; i<entities.length; i++) {
      var entity = entities[i];
      if (!entity.has('Shadow')) {
        console.log("entity.type");    // again, these two lines never print
        console.log(entity.type);
      }
      entity.visible = false;
    }   
    return this;
  },
}

```

**Comment by starwed** [comment] 2014-09-18 21:49
Thanks for the report.  Does this happen using DOM, Canvas, or both?

**Comment by danielmoniz** [comment] 2014-09-19 16:00
I was using Canvas. Trying it with DOM now (and using .visible, not .alpha), I am unable to reproduce the problem. So it looks like it's a canvas thing (I didn't think of that!).

**Comment by starwed** [comment] 2014-09-20 19:35
As an optimization, Crafty attempts to only draw regions of the canvas which have changed.  From your description, it sounds like you're seeing a bug in that system.  (That's probably why clicking on something fixes it -- the change flags that area to be redrawn.)

I can't see anything obviously wrong reading through Crafty's canvas renderer.  Maybe you could post the code that shows the issue?  It would help to see what specifically is triggering this.

(One debug tool for these issues is to set `Crafty.DrawManager.debugDirty = true`, which'll make it clearer which regions of the screen are flagged for drawing.)

**Comment by danielmoniz** [comment] 2014-10-08 15:59
Sorry for the delay in response. I have since put the game online, partially as an effort to be able to show you the difference.

Below are two websites with the same code (as of this writing), except that one uses DOM and the other Canvas. I tried turning on debugDirty, but it just put a red square around literally every tile and otherwise displayed the same thing (including the problem tiles). I'm not clear on what that mode is supposed to display.

I don't have instructions written up, but click the button "Start local hotseat game". You can select units with a left-click and move them with a right-click. Next turn is Spacebar (or just hit the grey button).

You can find the issue by moving units around, particularly to where they couldn't see before due to fog of war. I usually find black tiles by moving off the roads. You might also find roads that disappear. If I click on the black tiles, they re-appear, but they become back again when it's that player's turn next.

http://warm-tundra-8133.herokuapp.com/  -->  working app, looks good.
http://generals-glitchy.herokuapp.com/  --> after clicking around a bit, can see missing road/grass tiles

My code is not currently open source. I will be open-sourcing modules as I go, but given that it's my first serious JavaScript app, keeping things modular has been challenging. I will note, however, that rendering tiles works flawlessly using the DOM component. So something else is going on here. I have been meticulous with z-indexes as well. In cases where there are black tiles, the game knows it's the correct terrain type (as it will display its type in the bottom left corner). It just doesn't render.

Please let me know if that is helpful, and whether or not you are able to reproduce the issue.

**Comment by kevinsimper** [comment] 2014-10-13 09:28
I tried the game byt was not able to see what you are describing, sorry.

**Comment by danielmoniz** [comment] 2014-10-13 17:00
Below is a link to a few screenshots that demonstrate the issue. This happened the first time I loaded the game, meaning that it is not difficult for me to reproduce. Notice that the tiles only turn black when a unit can see them, ie. when the fog of war is being set to invisible.

Thes black boxes are common (I generally find one each game). Again, this issue is non-existent when using DOM instead of Canvas.

http://imgur.com/a/OyEZs

**Comment by heniotierra** [comment] 2014-10-21 13:04
I experience an apparently similar issue, however not involving tile maps or actively making entities invisible. My situation is like: 
I have a big sprite animation playing constantly as scenario. The scene also has a background Image in repeat mode, which moves constantly. After some minutes the background image reaches its limits, going completely out of the viewport, and at this point the entities which are moving are shown with black background (these entities use "static" sprites - as in "without animation" - with transparent background), besides, the z of these entities seem to get a bit weird, that is, they should be below a layer (column at the right side of the image) but are shown above it - maybe this would explain the entities disappearing for @danielmoniz , just a guess ofc.
A screenshot: http://goo.gl/kmwncb

**Comment by starwed** [comment] 2015-02-05 17:13
I still haven't been able to reproduce this for myself, and I still don't see anything in the code that would cause it.  I'm going to go ahead and close this, since it's hard to tell if it's a problem with Crafty or something caused by the particular game code.  Anyone should feel free to reopen this if they can provide a simpler test case!  

@heniotierra Did you ever figure out what was causing your issue?

**Closed as completed by starwed** 2015-02-05 17:13 UTC
Labels: status: pending review

**Comment by heniotierra** [comment] 2015-02-05 17:26
@starwed Well, no, but I noticed that when the glitch I mentioned occurs, the color of the sprites' [transparent] backgrounds change according to `Crafty.background`. However, there's nothing obvious to me that would trigger this glitch.

**Comment by danielmoniz** [comment] 2015-02-06 16:26
@starwed Yes, you can close this (for me, anyway; I can't speak for @heniotierra). I no longer have the issue if I choose Canvas. So presumably there is some situation in my game that caused the issue. That being said, I really didn't have a lot going on. Eg. I have absolutely no way to explain randomly placed black boxes - there is nothing in my code to create a black box, let alone a group of 9 of them that disappear as I move over them.

I'm guessing there is some really specific issue that crops up under very specific circumstances. Let's hope it was just my code! Regardless, I will report it in detail if it happens again.

Thanks!
