### ISSUE TITLE
Crafty object created from selectors doesn't have refs to entities

### ISSUE THREAD

**Issue by mpetrovic** [craftyjs/Crafty#91] opened 2011-05-31 17:05 UTC
From https://groups.google.com/forum/#!topic/craftyjs/rdx2ZZ6CuSY

From what Louis said, this is supposed to be the case. However, the entities are being converted into ints when they're added to the Crafty object.

I can see why they do this, since a single entity does the same. However, as a result the object is completely unlinked from the entities. As a result, something like this: http://jsfiddle.net/nneGE/ doesn't work. I would expect both boxes to be blue, but they are not.

**Comment by sorenbs** [comment] 2011-06-07 16:03
I think the .each function achieves this neatly. Take a look at this modified code http://jsfiddle.net/8ARv7/

Here i do
Crafty("Color").each(function(){ this.color("rgb(0,0,255)") });
instead of
Crafty("Color").color("rgb(0,0,255)");

The syntax is a bit bulky, but i think it is okay'ish.

If we should change this i think a nice direction to go would be something like:
Crafty("Color") constructs an object with all the entites and functions corresponding to functions in all the entities. The functions should be constructed in such a way that they will run through all the entities and call the correct function if they are present in the entity.
That would enable the shorthand Crafty("Color").color("rgb(0,0,255)"); even for functions that is not wrapped in  this.each(...

Would that be worth the trouble?

**Comment by mpetrovic** [comment] 2011-06-07 16:08
That's actually what I expected the functionality to be like before. Calling
a method on a collection should drill down to the individual entities as
well. Otherwise, what's the point of having the method on there at all?

**Comment by sorenbs** [comment] 2011-06-07 23:06
I have explored this approach of creating a dedicated group function whenever Crafty("...") is called by doing something like this in the for loop:

```
//Add group functions
var obj = entities[e];
for(key in obj) {
    if(this[key] === undefined && typeof(obj[key]) === "function") {
        var k = key;
        container[k] = function() {
            var args = arguments;
            this.each(function() {
                this[k].apply(this, args);
            });
        }
    }
} 
```

this approach makes the Crafty() function an order of magnitude slower (400 ms vs 10 ms for 1000 calls), but does provide the intended behavior. Unless we can make this much faster, i think we should just ask users to use the Crafty("...").each() paradigm.

**Comment by louisstow** [comment] 2011-06-07 23:20
The implementation of calling a function on a group of entities (based on a component) should be up to the component. All it needs to do is wrap the method inside `this.each`.

```
 this.each(function() {
      ...
 });
```

As for the selector returning Crafty objects, that should be easy to change and I think more useful.

**Comment by mpetrovic** [comment] 2011-06-08 03:32
I don't like the idea of forcing component developers to handle this for every component they write. That's the kind of thing we can easily abstract away, I think we should do it. 

As for the speed issue, I don't think it's a deal breaker on this. Anyone calling Crafty('selector') that much could fix their problem by caching results and just coding more efficiently. 

That said, if I had to guess, I'd say the biggest culprit on the time lost is building the new functions. That's something we could do in Crafty.c(). They give us an object, we run through the methods and wrap them in .each() calls, and extend Crafty('selector') with those.

**Comment by louisstow** [comment] 2011-06-08 03:43
I'll have a look to see if there's some optimizations available for one entity versus multiple. 

I don't think many people would be using it anyway.

**Comment by sorenbs** [comment] 2011-06-08 17:06
Cool. Looking forward to see what you will come up with.

I will for a moment allow myself to rethink the approach to entity lookup. Judging from the forums it looks like most people just want to access a specific entity that they have tagged with some special component, say Crafty("Hero1"). What they really want is for Crafty() to just return the single entity they ask for - easy. No need for group functions or this.each() wrapping. Just return the first entity.

Then some people want to manipulate a set of entities, say Crafty("Zombie"). I think asking users to just use Crafty("Zombie").each(...) is okay and actually more intuitive than the magic group functions. If somebody forgets to use .each() it will be pretty clear that only one entity is affected and hence easy to spot the error.

**Comment by austinh** [comment] 2012-07-31 21:15
Any update on this? I really agree with sorensb. The each function makes much more sense than magic group functions.

Also having Crafty(Crafty("Ball")[0]) just seems really counter-intuitive (and ugly).

**Comment by mpetrovic** [comment] 2012-10-29 19:45
Is this the consensus then?

Crafty('OneEntity') returns the actual entity.
Crafty('TwoEntities') returns a collection that developers must use .each() with to modify actual entities.
Crafty(1) returns the actual entity.

**Comment by louisstow** [comment] 2012-10-29 20:19
The problem I have with the Crafty('OneEntity') syntax is if there becomes more than one entity then the code breaks. Or if there is a collection that at one point only has one when there is expected to be more than one.

**Comment by sbyrnes321** [comment] 2013-04-25 02:33
I think this issue is long settled and can be closed. The behavior preferred by @mpetrovic is now implemented and clearly documented, with a specific note describing Louis's complaint and how to work around it:

> "If there is more than one match, the return value is an Array-like object listing the ID numbers of each matching entity. If there is exactly one match, the entity itself is returned. If you're not sure how many matches to expect, check the number of matches via Crafty(...).length. Alternatively, use Crafty(...).each(...), which works in all cases."

(from c233fff273)

**Comment by starwed** [comment] 2013-04-25 02:45
Looks like.  Closing as resolved.

**Closed as completed by starwed** 2013-04-25 02:45 UTC
