### ISSUE TITLE
NPM version still at 0.8

### ISSUE THREAD

**Issue by ghost** [craftyjs/Crafty#1186] opened 2018-07-18 10:34 UTC
Hi, I noticed that the following code doesn't run as intended with the latest distribution builds from the `release` and `develop` branch:

```js
square.bind('UpdateFrame', function(){
  this.rotation = this.rotation + 1;
});
```

However, using the build from the `testing` branch, the code above works as expected.

The [documentation on 2D](http://craftyjs.com/documentation/2d.html) uses the `testing` build by default and changing it to use either `release` or `develop` breaks the demo.

**Comment by starwed** [comment] 2018-07-22 17:18
I can't seem to reproduce -- if I [change the demo](http://jsbin.com/cofuqusopi/edit?html,js,output) in the docs to use the most recent release (0.9.0), it still works.

Could you check which version of Crafty are you using?  How did you install it?

**Comment by starwed** [comment] 2018-07-22 17:46
Aha, from looking at your other issue, I know what's going on -- I didn't update the node module with the 0.9 release.  :( 

I'll update the issue title, and see about fixing this.

**Comment by starwed** [comment] 2018-07-22 17:58
Hopefully fixed now?  The registry [now has 0.9.0](https://registry.npmjs.org/craftyjs) as the latest version, though the package page hasn't updated yet.

I'll leave this issue open until I've confirmed that the [package page](https://www.npmjs.com/package/craftyjs) is correct.

**Comment by starwed** [comment] 2018-07-22 18:25
Looks like this is a [known npm issue](https://status.npmjs.org/incidents/frcp18csxlks) (that's been ongoing since July 5?  :|).

I've confirmed that `npm install craftyjs` results in version 0.9, so closing this issue.

Thanks for the report!

**Closed as completed** 2018-07-22 20:33 UTC

**Comment by ghost** [comment] 2018-07-24 01:45
lovely! for some reason, I didn't get any notification that you replied to this ticket.
