### ISSUE TITLE
DOM sprites blinking in Chrome browser when image is not cached (such as loading from file://)

### ISSUE THREAD

**Issue by pawurb** [craftyjs/Crafty#668] opened 2013-12-25 21:55 UTC
I am having a bug with blinking DOM objects in Chrome browser. It looks like this:

http://www.youtube.com/watch?v=YTaia2DIDFs&feature=youtu.be

The green and red objects you can see are not even animated. Just static sprites, position constantly changed in EnterFrame using 2d#move() function.

I experience this issue only on Chrome browser running on Mac or Windows. On Ubuntu it works just fine (could be that drivers cannot fully use the webit gpu support which might be causing the problem). 

I can only assume it can be somehow connected with #656 .

Any clues will be appreciated.

**Comment by starwed** [comment] 2013-12-25 22:38
I don't think that would be related to #656, which is about the position on the sprite sheet not being set correctly.

Using Chrome on a Mac, I don't see that problem just displaying DOM sprites, so it's more specific than a general rendering problem.

Are you doing anything with the viewport?

If you could put together a jsfiddle (or show us the code somehow), that would be really useful.

**Comment by pawurb** [comment] 2013-12-26 17:31
https://github.com/pawurb/Siorb a repo of my project.

You can find the incorrectly rendered entities in src/entities

If you find it too messy let me know and I will try to reproduce bug with some simpler js fiddle. 

I am manually changing the x and y of viewport in relation to hero's position but problem persists even after disabling it.

**Comment by pawurb** [comment] 2013-12-29 15:18
Preparing the js fiddle for you I discovered that problem disappears when you host sprites on external website.

http://jsfiddle.net/chRuz/

If I run the same code on my local machine with 'runner1.png' loaded from local disc, blinking reappears. Do you have any idea what might be causing it ?

I checked it against the develop and master branches versions.

**Comment by kevinsimper** [comment] 2013-12-29 18:16
Are you using apache or loading by file://?

**Comment by pawurb** [comment] 2013-12-29 18:32
When I run it locally I open html file in a browser using file:// . Or if you ask how I load assets I use a path relative to the game html file.

**Comment by kevinsimper** [comment] 2013-12-29 18:46
You should check out http://harpjs.com/

It is like apache, buy 100x times easier.

There is problems when using file:// because browsers try to lock down what you can do, because of spyware and such, so functions like ajax do not work like it does on www.

**Comment by potomak** [comment] 2013-12-29 19:03
@kevinsimper I always use `file://` while debugging, there shouldn't be downside with it other than ajax requests as you've said.

@pawurb you should note console errors if the `file://` protocol is preventing resources loading.

The _fastest_ way to set an HTTP server to serve static resources is using Python's `SimpleHTTPServer`:

``` sh
$ python -m SimpleHTTPServer
```

More details at http://www.linuxjournal.com/content/tech-tip-really-simple-http-server-python

If you're using Grunt I also suggest [`grunt-contrib-connect`](https://github.com/gruntjs/grunt-contrib-connect).

**Comment by pawurb** [comment] 2013-12-29 19:50
@potomak I did not get any console errors. Images were loaded correctly but were blinking.

I could not get it working with `grunt-contrib-connect` althought I ran the server and changed assets path to use it. Images were still blinking. 

However `SimpleHTTPServer` works like wonder. I can run the html file using `file://` protocol but assets have to be served using server. Any idea why and should it be treated as a crafty bug ?

Thanks a lot for your help !

**Comment by kevinsimper** [comment] 2013-12-29 20:48
You should checkout Harpjs which is a Node.js module as mentioned before, it also provide coffeescript support:

`npm install harp -g``

and then just `harp serve` in the dir you want to run from: http://localhost:9000

The assets does not work because of the progress event is deactivated.

Since it is not a crafty issue i am going to close this.

**Comment by starwed** [comment] 2013-12-29 21:27
Hehe, searching google for this issue actually turned up a thread in the crafty group as the first result.  [This thread](https://groups.google.com/forum/#!topic/craftyjs/FJ1M0gFiPTs) describes the issue and it's cause -- it has to do with how chrome caches local images.

The blinking was caused by chrome reloading the image every frame.  I suspect there _is_ something we could do to mitigate this, so reopening.  

Currently we set the background image of a DOM sprite every time it's drawn.  We could easily check to see whether it's changed, and only set that property in cases where it had.

**Comment by starwed** [comment] 2013-12-30 00:12
[This chromium bug](http://code.google.com/p/chromium/issues/detail?id=102706) is probably relevant.  (We display a sprite by using the `background-image` property.)

**Comment by roborourke** [comment] 2014-01-03 14:51
I saw behaviour like this when my sprite was set up as a shared part of a component eg:

``` js
Crafty.c( 'Shape', {
    init: function() { 
       this.addComponent( 'circle' );
    },
    _sprite: Crafty.sprite(100, 'gfx/sprite.png', { circle: [0,0] })
} );
for( i=0; i<20; i++ )
    Crafty.e( '2D, DOM, Shape' );
```

When I created the sprites in a more global scope the flickering disappeared.

``` js
Crafty.sprite(100, 'gfx/sprite.png', { circle: [0,0] });
Crafty.c( 'Shape', {
     init: function() {
         this.addComponent( 'circle' );
     }
} );
for( i=0; i<20; i++ )
    Crafty.e( '2D, DOM, Shape' );
```

The example is reduced down somewhat, in my case there's just some code to add a random start position to the shapes. Let me know if you want to see a full example or if this helps at all.

**Comment by starwed** [comment] 2014-01-04 22:40
@sanchothefat 

`Crafty.sprite` is kind of like a factory that defines components globally.  Calling it multiple times within components, you're redefining what the "circle" component is each time.  I'm not surprised that would cause some weird graphical issues, especially if it's something you do each frame.

I don't think it has anything to do with this particular bug.

**Comment by anilmaurya** [comment] 2014-09-06 19:33
@starwed Any update on this Issue ? I am facing this issue.

**Closed as completed** 2015-02-07 03:15 UTC
