### ISSUE TITLE
[NodeJS] `Crafty.init is not a function.`

### ISSUE THREAD

**Issue by 0xf0xx0** [craftyjs/Crafty#1198] opened 2018-12-02 16:37 UTC
Im trying to get Crafty to work. I tried it in VSCode and on RunKit, and both threw the same error.
```css
TypeError: Crafty.init is not a function
Level1.js:3
    at Object.<anonymous> (/Users/gingkathfox/Desktop/Overtime-Game/Level1.js:3:8)
    at Module._compile (module.js:640:14)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
 code file: [Level1.js.zip](https://github.com/craftyjs/Crafty/files/2637132/Level1.js.zip)

**Comment by starwed** [comment] 2018-12-02 17:13
Hmm, I can't reproduce in a normal context.  

Here is an [updated version of the npm example](https://github.com/starwed/craftyjs-npm-example).  When I run that locally (per the README instructions), crafty is imported correctly and the 'game' works ok.

So it seems that craftyjs isn't being found correctly when you're requiring it, possibly due to the way your environment is setup.  I'm not familiar with how node modules are used within VSCode or RunKit, could you provide a bit of background on what you're trying to accomplish?

**Comment by 0xf0xx0** [comment] 2018-12-02 23:08
Im helping develop a game, and since JS is the only language I know well, I wanted the engine to be in JS. I found Crafty, and decided to use it. 
I don't think VSCode does anything to the node modules, it calls node to debug and run it.

**Comment by starwed** [comment] 2018-12-02 23:40
VSCode is written in [Electron](https://electronjs.org/), so it probably does have some way of running js as if it were in a browser, using html rendering.  I've only ever used it as an editor, though, since that's its primary focus.  How are you attempting to invoke `Level1.js` from within VSCode?

I'd suspect you'll probably find it easier to follow the [example](https://github.com/starwed/craftyjs-npm-example), spinning up a node server locally to run your code in a browser.   (You can just clone the repo as a starting point.) The example uses browserify to assemble everything, but it should be possible to use alternatives  like webpack if you like.

**Comment by starwed** [comment] 2018-12-08 20:51
Since I couldn't reproduce, closing the issue.

Feel free to reopen with more details!

**Closed as completed by starwed** 2018-12-08 20:51 UTC

**Comment by 0xf0xx0** [comment] 2019-01-12 15:02
Just realized i forgot about this XD
i got the engine to work (as you know from my later issues), i cant remember how i fixed it though.
