### ISSUE TITLE
Tween animation leaves a "trace"

### ISSUE THREAD

**Issue by ManuelRauber** [craftyjs/Crafty#564] opened 2013-10-21 22:26 UTC
I'm currently writing an Windows 8 App with CraftyJS. The first start is very promising, I like the way who crafty works. 

Unfortunately I have a little problem. Please take a look at the attached screenshot. 

I created a gist for the code, please take a look here: https://gist.github.com/ManuelRauber/7241b75d611a7726327c

Please let me know, if you need further information about this.

I have currently no clue, what's going on here.

Thanks for your help!
![screenshot](https://f.cloud.github.com/assets/740791/1377049/9796d9f2-3a9f-11e3-88a1-cc78ae9053ca.png)

Original post was on Google groups: https://groups.google.com/forum/#!topic/craftyjs/2XLw9Z-CwEs

**Comment by starwed** [comment] 2013-10-22 15:19
Hi, the gist doesn't include quite enough code to easily reproduce the issue.  (If I just load those two files I still get some errors about a Game object not existing.) Could you create a jsfiddle or a complete example of the problem?

**Comment by ManuelRauber** [comment] 2013-10-22 18:45
Can you compile for Windows 8 Store Apps? It's going to be an open source app: https://github.com/ManuelRauber/StupidRobot

Give me a ping, if you want me to extract the relevant parts to a jsfiddle.

**Comment by starwed** [comment] 2013-10-23 01:29
@ManuelRauber A jsfiddle would be the best way, since I don't have any way right now to test Windows 8 stuff!  :)

**Comment by kevinsimper** [comment] 2013-11-20 22:33
@ManuelRauber Did this problem still happen to you?

**Comment by starwed** [comment] 2013-12-08 06:03
You might want to try the 0.6.1 release; there was a bug fix for a very similar issue.

I'm going to close this for now, do let us know if it still occurs in 0.6.1.

**Closed as completed by starwed** 2013-12-08 06:03 UTC
