### ISSUE TITLE
viewport.scale and placing DOM entities

### ISSUE THREAD

**Issue by tamagokun** [craftyjs/Crafty#390] opened 2012-12-18 14:14 UTC
(using develop branch)

I am currently using the canvas side of Crafty to place entities and then scale them x2. This works great, but since needing to add Text entities via the DOM, the position of the text isn't calculating properly and doesn't show up on screen.

If I don't scale the viewport, things work as intended.

I will try to reproduce this with a jsFiddle.

**Comment by tamagokun** [comment] 2013-02-22 01:08
I have made some more ground with this issue:

_Here is a jsfiddle to demonstrate my findings: http://jsfiddle.net/4Zq7u/1/_

It looks as though dimensions set with canvas elements aren't inheriting scaled positioning, which is odd because when I am using sprites, things are getting scaled appropriately. When using a DOM element, its position is being set properly.

Is this intended functionality?

**Comment by bb7555** [comment] 2013-02-22 04:16
I am not a contributor to the crafty repo, only an avid user. However, this is odd, and does seem like a bug to me, too.

**Comment by thehack** [comment] 2013-02-22 09:20
You may have already seen this, but I have written up a description of my struggles with viewport.scale: https://github.com/craftyjs/Crafty/issues/339

**Comment by bb7555** [comment] 2013-02-22 18:02
hmmm...interesting....I have some spare time maybe I should make a branch and see if this bug can be resolved

**Comment by tamagokun** [comment] 2013-02-23 18:23
I can take a stab at this also, just wanted to get this logged in case anyone more familiar with the crafty source knew what was going on with this.

**Comment by starwed** [comment] 2013-05-12 06:29
The issue is that calling scale before any canvas entities have been created does nothing, and the canvas isn't created until a "Canvas" element exists.  You can confirm this by moving the call to scale in the jsfiddle until after the first element has been made.

So, the canvas is only created on demand, and `viewport.scale()` only sets the scale of the canvas if it exists.  I think the fix would be for canvas.init to check `Crafty.viewport._zoom` and autoscale on creation.    Alternatively we could create the canvas when scale is called, but I prefer the former method, since there's no point creating a canvas element unless it'll be used.

**Comment by starwed** [comment] 2013-05-14 19:22
Should be fixed now.

**Closed as completed by starwed** 2013-05-14 19:22 UTC
