### ISSUE TITLE
Inputs, textareas don't work. pls help.

### ISSUE THREAD

**Issue by lgm313** [craftyjs/Crafty#373] opened 2012-11-05 07:16 UTC
```
var entity=Crafty.e("2D, DOM,HTML")
        .attr({x:0, y:20, w:100})
        .replace("<input id='test' type=\"text\" size=\"20\" style=\"background-color:#FFFFFF\">");
```

as you see above code,  i wanna display a input component on the canvas and allow user input something, but now ,it cannot input at all. BTY, i am using the v1.5.3 lib. pls help!

**Comment by kevinsimper** [comment] 2012-11-06 10:14
Could you make a jsfiddle with the problem? Else it is really hard to solve your problem.

**Comment by sntran** [comment] 2012-11-28 01:05
I can confirm that it does not work. I can't type in it, but I can delete existing text.

http://jsfiddle.net/EjFak/3/

Tested it in latest Chrome.

Same problem as #303

**Comment by starwed** [comment] 2013-05-01 02:01
Closing as a dupe of #303

**Closed as completed by starwed** 2013-05-01 02:01 UTC
