### ISSUE TITLE
.textFont has no effect

### ISSUE THREAD

**Issue by cawoodm** [craftyjs/Crafty#413] opened 2013-02-02 11:15 UTC
Using the latest crafty.js 0.5.3 I've noticed .textFont() has no effect. The following 3 code blocks are equivalent:

```
Crafty.e("LeftPoints, DOM, 2D, Color, Text")
    .attr({ x: 20, y: 10, w: 100, h: 20, points: 0 })
    .text("0 Points")
    .textColor('#FFFF22', 0.8);
```

```
Crafty.e("LeftPoints, DOM, 2D, Color, Text")
    .attr({ x: 20, y: 10, w: 100, h: 20, points: 0 })
    .text("0 Points")
    .textColor('#FFFF22', 0.8)
    .textFont('family', 'Arial');
```

```
Crafty.e("LeftPoints, DOM, 2D, Color, Text")
    .attr({ x: 20, y: 10, w: 100, h: 20, points: 0 })
    .text("0 Points")
    .textColor('#FFFF22', 0.8)
    .textFont({family:  'Arial'});
```

In all cases the text font is not set (and renders as Times New Roman - the browser default).

**Comment by starwed** [comment] 2013-04-26 06:03
The problem is that when setting the `font` property (which `textfont()` does) you can't set `font-family` or `font-size` separately; they must both be included.  This is mentioned [here](https://developer.mozilla.org/en-US/docs/CSS/font).  This is also the cause of bug #337, so I'll close this as a dupe of that.

**Closed as completed** 2013-04-26 06:07 UTC
