### ISSUE TITLE
collision no longer works with circle in 0.8

### ISSUE THREAD

**Issue by TommyDong1998** [craftyjs/Crafty#1139] opened 2017-06-01 23:58 UTC
collision no longer works with circle in 0.8
I saw that in older jsfiddle circle work with collision
but they dont work anymore

**Comment by mucaho** [comment] 2017-06-04 08:15
link the jsfiddle please

**Comment by starwed** [comment] 2017-07-09 02:33
I can't reproduce, so closing.  Feel free to reopen with steps to reproduce (or example code that shows the problem.)

**Closed as completed by starwed** 2017-07-09 02:33 UTC
